name: Build and push docker image

on:
  push:
    branches: [ "main" ]

variables:
  IMAGE_NAME: my-docker-image
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release
        run: npm run release
