name: Build and push docker image

on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u gelugu -p ${{secrets.DOCKER_HUB_TOKEN}}
      - name: Build the Docker image
        run: docker build --tag gelugu/gelugu-music:0.1.0 --file Dockerfile .
      - name: Push the Docker image
        run: docker push gelugu/my-space:0.1.0
